### ISSUE TITLE
Remove url_for from details-page

### ISSUE THREAD

**Issue by Krassmus** [studip/PluginMarket#48]
url_for is not flexible with adding parameters and also it should be link_for instead url_for. But I replace it with PluginEngine::getLink.

**Comment by tleilax** [comment]
`(link|url)_for` is about as flexible as `PluginEngine::getURL()` regarding parameters. If there is a general techincal problem with `(link|url)_for`, this should be fixed and not worked around. Using anything else than `(link|url)_for` in a trails' view for linking to the same controller/app kinda smells bad and therefore should not be used.

But that's just my 2 cents...

**Comment by Krassmus** [comment]
Then how do you write PluginEngine::getLink($plugin, array('username' => get_username()), "foo/bar") with url_for? I cannot see any documentation about that in trails. 

url_for also violates our coding standards as it contains underscore instead of camelCase.

And in templates we should use link_for instead of url_for.

**Comment by tleilax** [comment]
Since the controller is most probably derived from a `StudipController`, this is [`$controller->url_for('foo/bar', array('username' => get_username())`](http://develop.studip.de/trac/browser/trunk/app/controllers/studip_controller.php#L182), as used for a long time in most of the trails views in the core system.

And yes, I see the theoretical problem with `url_for()` and `link_for()` but have a look at `app/views` and compare the usage of both. If that really is a problem and not just a theoretical one, this should look differently...

Do I really have to reply the coding standards objection? You're using `get_username()` for your example, all trails controller actions are in snake case and nobody ever complains. Cause it's totally fine since it's part of an external library we use for the core.

But since we use it, we should use it as it is supposed to be used. That's my main point (besides **consistency** and **readability**) for `(link|url)_for` and against using `PluginEngine` in trails views.
